### ISSUE TITLE
更新到2.0后，老是偶尔闪退。

### ISSUE THREAD

**Issue by Tyrant2013** [MobClub/MOBFoundation#2]
截取到的闪退的地方就如下图所示：
![qq20160613-0 2x](https://cloud.githubusercontent.com/assets/3370584/16002329/a092e436-3189-11e6-8ebb-97fe8048e648.png)

**Comment by JinghuangLiu** [comment]
好的，多谢反馈，今天内修复。

**Comment by Tyrant2013** [comment]
好的，最新那2.0.1就是修复这个问题的吗？

**Comment by patgdut** [comment]
2.0.1 后台切换到前台经常 Crash...坑,回到1.5.3了...

**Comment by Tyrant2013** [comment]
更新到2.0.1后闪退的更厉害了，我还是换回1.5.3好了。

**Comment by JinghuangLiu** [comment]
麻烦联系下我们官方技术 mob.com

发自我的 iPhone
