### ISSUE TITLE
Miss file 

### ISSUE THREAD

**Issue by ArbifyFun** [MobClub/MOBFoundation#3]
podspecs header路径有问题吧。
![97d86674-4efd-4f36-bc3a-cf4612f13429](https://cloud.githubusercontent.com/assets/9291649/20202385/c9ac4b1e-a7f9-11e6-8b72-dfc9fd4b59b2.png)

**Comment by JinghuangLiu** [comment]
用最新的公共库能解决这个问题

发自我的 iPhone

**Comment by FlyingNoob** [comment]
就是最新的2.2.3版本

**Comment by JinghuangLiu** [comment]
mob.com 底部有QQ号——可以联系下我们能技术支持

发自我的 iPhone

**Comment by FlyingNoob** [comment]
@JinghuangLiu 技术支持丢一个集成文档就没有下文了，也是够了！

**Comment by JinghuangLiu** [comment]
你那边用的ShareSDK的版本应该是旧的，建议用最新的。不然MOBF用v2.2.0（前几版本的）之前应该就可以了。

发自我的 iPhone
