### ISSUE TITLE
启动时，Mob 长时间阻塞主线程导致 App 闪退

### ISSUE THREAD

**Issue by EkkoG** [MobClub/MOBFoundation#6]
![image](https://cloud.githubusercontent.com/assets/3138493/22054668/b3a4d9b2-dd91-11e6-8752-4d72ecc88255.png)

iOS 10.0.2

**Comment by JinghuangLiu** [comment]
版本是多少的？这个问题应该已经修复，如果不是最新版本，使用最新版本即可。

发自我的 iPhone

**Comment by EkkoG** [comment]
不好意思，忘记反馈 SDK 版本，目前在使用的版本是 2.2.11，不是最新版本，我更新一下看看


在 2017年1月18日 下午3:35:07, 刘靖煌 (notifications@github.com) 写到:

版本是多少的？这个问题应该已经修复，如果不是最新版本，使用最新版本即可。

发自我的 iPhone

> 在 2017年1月18日，下午3:21，Kevin <notifications@github.com> 写道：
>
>
> iOS 10.0.2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MobClub/MOBFoundation/issues/6#issuecomment-273404265>,
or mute the thread

**Comment by JinghuangLiu** [comment]
好的

发自我的 iPhone
